import React from 'react'
import './style.css'


function Price() {
  return React.createElement( 'section',{className:'pricing py-5'},
  React.createElement('div',{className:'container'},
  React.createElement('div',{className:'row'},
  React.createElement('div',{className:'col-lg-4'},
  React.createElement('div',{className:'card mb-5 mb-lg-0'},
  React.createElement('div',{className:'card-body'},
  React.createElement('h5',{className:'card-title text-muted text-uppercase text-center'},'FREE'),
  React.createElement('h6',{className:'card-price text-center'},'$0',
  React.createElement('span',{className:'period'},'/month')),
  React.createElement('hr',null),
  React.createElement('ul',{className:'fa-ul'},React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Single User'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'5GB Storage'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Unlimited Public Projects'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Community Access'),
  React.createElement('li',{className:'text-muted'},
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Unlimited Private Projects'),
  React.createElement('li',{className:'text-muted'},
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Dedicated Phone Support'),
  React.createElement('li',{className:'text-muted'},
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Free Subdomain'),
  React.createElement('li',{className:'text-muted'},
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Monthly Status Reports'),),
  React.createElement('div',{className:'d-grid'},
  React.createElement('a',{className:'btn btn-primary text-uppercase'},'Subscribe')) ) )),

  React.createElement('div',{className:'col-lg-4'},
  React.createElement('div',{className:'card mb-5 mb-lg-0'},
  React.createElement('div',{className:'card-body'},
  React.createElement('h5',{className:'card-title text-muted text-uppercase text-center'},'PLUS'),
  React.createElement('h6',{className:'card-price text-center'},'$9',
  React.createElement('span',{className:'period'},'/month')),
  React.createElement('hr',null),
  React.createElement('ul',{className:'fa-ul'},
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),React.createElement('strong',null),'5 Users'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'50GB Storage'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Unlimited Public Projects'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Community Access'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Unlimited Private Projects'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Dedicated Phone Support'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Free Subdomain'),
  React.createElement('li',{className:'text-muted'},
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Monthly Status Reports'),),
  React.createElement('div',{className:'d-grid'},
  React.createElement('a',{className:'btn btn-primary text-uppercase'},'Subscribe')) ) )),

  React.createElement('div',{className:'col-lg-4'},
  React.createElement('div',{className:'card mb-5 mb-lg-0'},
  React.createElement('div',{className:'card-body'},
  React.createElement('h5',{className:'card-title text-muted text-uppercase text-center'},'PRO'),
  React.createElement('h6',{className:'card-price text-center'},'$49',
  React.createElement('span',{className:'period'},'/month')),
  React.createElement('hr',null),
  React.createElement('ul',{className:'fa-ul'},
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),React.createElement('strong',null),'Unlimited Users'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'150GB Storage'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Unlimited Public Projects'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-check'},)),'Community Access'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Unlimited Private Projects'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Dedicated Phone Support'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),React.createElement('strong',null,'Unlimited'),'Free Subdomain'),
  React.createElement('li',null,
  React.createElement('span',{className:'fa-li'},React.createElement('i',{className:'fa fa-times'},)),'Monthly Status Reports'),),
  React.createElement('div',{className:'d-grid'},
  React.createElement('a',{className:'btn btn-primary text-uppercase'},'Subscribe')) ) )),




   ) ));
}

export default Price